name: Generate from Channel and Upload

on:
  workflow_dispatch:
    inputs:
      channel_handle:
        description: "YouTube channel handle or ID (e.g., @SwaruuOficial or UC...)"
        required: true
        default: "@SwaruuOficial"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      GOOGLE_OAUTH_CLIENT_JSON: ${{ secrets.GOOGLE_OAUTH_CLIENT_JSON }}
      # YouTube OAuth token (JSON content)
      YOUTUBE_TOKEN_JSON: ${{ secrets.YOUTUBE_TOKEN_JSON }}
      # Drive OAuth token (JSON content)
      GOOGLE_OAUTH_TOKEN_JSON: ${{ secrets.GOOGLE_OAUTH_TOKEN_JSON }}
      DRIVE_PARENT_FOLDER_ID: ${{ secrets.DRIVE_PARENT_FOLDER_ID }}
      SLOP_LOG_LEVEL: INFO
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate from channel and upload
        run: |
          python -m slop.cli generate_from_channel_if_new \
            --channel-handle "${{ inputs.channel_handle }}" \
            --output-dir outputs \
            --upload \
            --drive-upload \
            --credentials-dir "${{ github.workspace }}"


