name: generate-and-upload

on:
  workflow_dispatch:

concurrency:
  group: generate-and-upload
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      OAUTH_CLIENT_JSON: ${{ secrets.OAUTH_CLIENT_JSON }}
      DRIVE_TOKEN_JSON: ${{ secrets.DRIVE_TOKEN_JSON }}
      DRIVE_PARENT_FOLDER_ID: ${{ secrets.DRIVE_PARENT_FOLDER_ID }}
      YOUTUBE_TOKEN_JSON: ${{ secrets.YOUTUBE_TOKEN_JSON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python 3.11 via uv
        run: uv python install 3.11

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate and upload to YouTube and Google Drive
        run: uv run --python 3.11 slop generate

      - name: Upload artifact (latest video)
        uses: actions/upload-artifact@v4
        with:
          name: latest-video
          path: outputs/*.mp4
          if-no-files-found: ignore


